services:
  tests:
    image: buildkite/plugin-tester:v4.3.0
    volumes:
      - ".:/plugin"

  lint:
    image: buildkite/plugin-linter:v3.0.0
    command: ['--id', 'custom-checkout']
    volumes:
      - ".:/plugin:ro"