name: Custom-checkout-buildkite-plugin
description: A refined plugin for handling repository checkouts in Buildkite
author: https://github.com/buildkite
version: "1.0.0"
requirements: []

configuration:
  properties:
    skip_checkout:
      type: boolean
      default: false
      description: "If true, skips the checkout process."
    delete_checkout:
      type: boolean
      default: false
      description: "If true, deletes the checkout directory after the build."
    checkout_path:
      type: string
      description: "Custom path for checking out repositories."
    interpolate_checkout_path:
      type: string
      description: "Checkout path with environment variables to interpolate."
    repos:
      type: array
      description: "List of repositories to checkout."
      items:
        type: object
        properties:
          url:
            type: string
            description: "Repository Git URL."
          mirror_url:
            type: string
            description: "Optional mirror URL for faster or local cloning."
          ref:
            type: string
            description: "Branch, tag, or commit to checkout."
          checkout_path:
            type: string
            description: "Directory where this repository will be cloned. Accepts relative paths (e.g., 'my-repo') for subdirectories, or absolute paths (e.g., '/tmp/checkout'). Defaults to the main directory if not specified, or relative if multiple repositories are configured."
          ssh_key_path:
            type: string
            description: "Path to SSH key for repository access."
          clone_flags:
            type: array
            items:
              type: string
            description: "Additional flags for git clone."
          fetch:
            type: boolean
            default: false
            description: "Performs a git fetch operation after clone and before checkout. Useful for shallow clones when fetching specific commits."
          fetch_flags:
            type: array
            items:
              type: string
            description: "Additional flags for git fetch command (e.g., '--depth=1'). Only used when fetch is enabled."
        required:
          - url
  additionalProperties: false
