steps:
  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.3.0:

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**

  - label: ":Tests: Docker-compose"
    plugins:
      - docker-compose#v5.5.0:
          run: tests
